# Generated by Django 3.2.25 on 2025-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0073_auto_20250305_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsunit',
            name='criteria_delay',
            field=models.FloatField(default=0),
        ),
    ]
