# Generated by Django 3.2.25 on 2025-08-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0074_pbsunit_criteria_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuredata',
            name='relevant_failure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='service_affecting_failure',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('random', 'Random')], default='No', max_length=600),
        ),
    ]
